### ISSUE TITLE
It seems we've been unable to process your payment properly

### ISSUE THREAD

**Issue by itcdsc** [omise/omise-woocommerce#119]
I get this error in woocommerce, both in Live and Demo.

It seems we've been unable to process your payment properly:
Note that your payment may have already been processed. Please contact our support team if you have any questions.

**Comment by guzzilar** [comment]
@itcdsc Hi, may I know what payment method you were testing? Was it Credit Card?
And, may I know your WordPress, WooCommerce, and Omise-WooCommerce versions you are currently using?

**Comment by itcdsc** [comment]
@guzzilar
Wordpress: 5.2.2
WooCommerce: 3.6.5
Omise: 3.4

It was a demo Credit Card. 4242 4242 4242 4242

**Comment by guzzilar** [comment]
@itcdsc Could you let us know your email that is registered with Omise?
Our support email is support@omise.co.

So far I've tested with the version you gave and it seems to be working as normal. I would like to check more at the payment transaction log.

**Comment by guzzilar** [comment]
@itcdsc Hi, I believed this issue has been solved already?
I'm closing the ticket now. Feel free to re-open again if you are still facing the issue.

Cheers.
