### ISSUE TITLE
test_omise_customer_id does not exists

### ISSUE THREAD

**Issue by wickstargazer** [omise/omise-woocommerce#135]
Hi i am testing on woocommerce and i get this error

`Trying to get property 'test_omise_customer_id' of non-object in <b>/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/omise/includes/gateway/class-omise-payment-creditcard.php`

WordPress 5.2.3 
omise latest version
woocomerce 3.6.5
--

**Comment by guzzilar** [comment]
@wickstargazer Hi, can I have more detail about this?
In which screen did you get this error and what was happening before the error?

**Comment by wickstargazer** [comment]
Hi, so this happens in the checkout page, the charge page. It seems like the test_omise_customer_id does not exist in the taxonomy or attribute of the user

**Comment by aashishgurung** [comment]
We’re going to close this since there hasn’t been any activity on this issue for a while. If you think it's still relevant, please feel free to reopen it with more details and we’ll take another look.
