### ISSUE TITLE
New version with TESCO create bug - new order notifications cannot be sent

### ISSUE THREAD

**Issue by Sogofactory** [omise/omise-woocommerce#136]
New version with TESCO create bug - new order notifications cannot be sent

**Comment by guzzilar** [comment]
@Sogofactory Hi, thanks for reporting.
We have received the same report from users. I'd mark this ticket as `bug` and `in progress` now.

Sorry for the inconvenience.

**Comment by guzzilar** [comment]
@Sogofactory Hi, we have released the fix of this issue at Omise-WooCommerce v3.8. Available at https://wordpress.org/plugins/omise

Thanks for reporting us the issue. I'm going to close this ticket after 24 hrs (feel free to reopen if you are still facing the issue)
