### ISSUE TITLE
It seems we've been unable to process your payment properly:

### ISSUE THREAD

**Issue by bennybravo99** [omise/omise-woocommerce#148]
hello 

we are now in test payment mode with our woocommerce setup but getting the following message after submitting a test card payment

"It seems we've been unable to process your payment properly:"

Wordpress: 5.2.2
WooCommerce: 3.8.0
Omise: 3.9

we use a test card Credit Card. 4242424242424242

**Comment by jacstn** [comment]
@bennybravo99 did you try with both 3ds and non3ds options?

**Comment by bennybravo99** [comment]
Hello

We tried with 3ds and it works - the payment is success, if 3ds is disabled
we get the payment error message

thanks

ben


Ben Yermak | Chief Digital Officer
| mobile: 0849194435
| phone: 020385879
| email: ben@gopr.co.th
| address: 32/29 Sino-Thai Tower, Sukhumvit 21, Asoke, Bangkok

**Comment by jacstn** [comment]
@bennybravo99 that is because in omise account configuration you have 3ds on, but in wordpress you had off.
It has been changed and new release that is coming soon will be automatically checking if 3ds is on, and work accordingly.
