### ISSUE TITLE
It seems we've been unable to process your payment properly: Unknown error. (Bad Response)

### ISSUE THREAD

**Issue by mauimao17** [omise/omise-woocommerce#174]
Hi,

I'm having this error on checkout using Omise Internet Banking method. Credit card method works fine. just when I choose Internet banking this error pops up. Please help!

Thank you

WooCommerce version: 4.2.2
WordPress version: 5.4.2
PHP version: 7.3.19
Omise version: 3.11

**Comment by aashishgurung** [comment]
We’re going to close this since this has already been resolved. If you think it's still relevant, please feel free to reopen it with more details and we’ll take another look. Thank you.
