### ISSUE TITLE
Change position of Omise Payment Settings in WooCommerce My Account

### ISSUE THREAD

**Issue by fabiomail** [omise/omise-woocommerce#191]
I am testing your Omise WooCommerce plugin integration and I have a suggestion for future plugin updates:

Currently, the "Omise Settings" (see: https://drive.google.com/file/d/1Wa23br92YHElS4TVRPD5VpH7KV3yT573/view?usp=sharing ) are showing in the main WooCommerce "My Account" page (Dashboard). 

However, I believe the correct place to embed these settings would be under "Payment methods" like Stripe is doing.

Or, at least, It would be nice to have a separate end-point and/or a shortcode, so that this portion can be embedded wherever needed with a page-builder.

I look forward to hearing from your opinion on this.

Best regards,

**Comment by fabiomail** [comment]
Hello, any feedback on this?

**Comment by mayurkathale** [comment]
@fabiomail Thanks for your suggestion.
We are keeping general setting such as API Keys, test mode etc. separated from particular payment method related settings. This is the main reason keeping Omise setting outside of WooCommerce setting. Unlike stripe having general settings included Stripe card payment section.

**Comment by fabiomail** [comment]
Hi, thank you for your response. I actually see Omise settings under WooCommerce setting - just not under Payment settings, but in the main WooCommerce My Account page. 

How can I pull Omise settings to display them wherever I want/need? (example, using a Page Builder, such as Elementor)?

**Comment by mayurkathale** [comment]
@fabiomail WooCommerce My Account has Omise setting section is to save card details. we currently do not support this section to be pull by short-code or pagebuilder.

**Comment by fabiomail** [comment]
Yes, this is exactly what I was talking about. I believe adding the saved credit card details section in the main Woo My Account page is not the right place - it should go under "Payment Settings" instead. 

Not everybody uses the default My Account page (if you customize it), thus losing this important setting.  

Is this something you can consider?
