### ISSUE TITLE
Could you build the omise module for Prestashop V1.7

### ISSUE THREAD

**Issue by thawatchai197** [omise/omise-woocommerce#195]
Now our website is made by Prestashop V1.7.x. In the past our website based on Prestashop V1.6. Could you please create the module to support Prestashop V1.7?

**Comment by aashishgurung** [comment]
We are closing this issue since it is not related to this repo. Regarding Prestashop module, the work on it is currently on hold. While we understand that it could be useful to some users, we have other priorities that we need to focus on. Thank you.
