### ISSUE TITLE
is it compatible with WooCommerce 5.x?

### ISSUE THREAD

**Issue by chrisvidal** [omise/omise-woocommerce#217]
The versions of the following plugins you're running haven't been tested with WooCommerce 5.0. Please update them or confirm compatibility before updating WooCommerce, or you may experience issues

Plugin | Tested up to WooCommerce version
-- | --
Omise Payment Gateway | unknown

**Comment by pjrobertson** [comment]
@kan98 @tookaa2 @nimitomise - sorry for the ping. But are any of you able to confirm if this plugin is compatible with WooCommerce 5.x? If so, can the docs be updated to reflect this?

The official docs state this plugin is [only compatible up to WooCommerce 4.3.0](https://www.omise.co/woocommerce-plugin), however WooCommerce 5.0 was released 10 months ago (Feb 2021). 

My guess is it's compatible, it just needs a docs update.

Thanks!

**Comment by kan98** [comment]
Hi @pjrobertson, the plugin should work fine on the latest versions of Woocommerce. We have tested against the latest versions. But of course, please let us know if there are any issues.

> can the docs be updated to reflect this?

Yes, thanks for letting us know. We will update the documentation to reflect the recent changes.

**Comment by pjrobertson** [comment]
Thanks @kan98 for the speed response. I will update you if we find any issues

**Comment by hellcoderGIT** [comment]
This plugin unfortunately seems to not get much attention anymore, latest version stopped working either with the last release or maybe the newer PHP versions, support center mentioned that 8.x Version of PHP is not supported and suggests php version downgrade (great...).

Website has also not been updated to reflect support for 5.x yet.

> CRITICAL Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method OmisePluginHelperMailer::disable_merchant_order_on_hold() cannot be called statically in /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php:305
> Stack trace:
> #0 /customers/4/2/3/website.com/httpd.www/wp-includes/plugin.php(189): WP_Hook->apply_filters('info@website...', Array)
> #1 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(399): apply_filters('woocommerce_ema...', 'info@website...', Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Email_New_Order))
> #2 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(109): WC_Email->get_recipient()
> #3 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(303): WC_Email_New_Order->trigger(15431, Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #4 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
> #5 /customers/4/2/3/website.com/httpd.www/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
> #6 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array('woocommerce_ord...', Array)
> #7 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(303): WC_Emails::send_transactional_email(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #8 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
> #9 /customers/4/2/3/website.com/httpd.www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
> #10 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-order.php(373): do_action('woocommerce_ord...', 15431, Object(Automattic\WooCommerce\Admin\Overrides\Order))
> #11 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-order.php(222): WC_Order->status_transition()
> #12 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-order.php(120): WC_Order->save()
> #13 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/omise/includes/gateway/class-omise-payment-creditcard.php(320): WC_Order->payment_complete()
> #14 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/omise/includes/gateway/class-omise-payment.php(214): Omise_Payment_Creditcard->result(15431, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(OmiseCharge))
> #15 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(980): Omise_Payment->process_payment(15431)
> #16 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1195): WC_Checkout->process_order_payment(15431, 'omise')
> #17 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(461): WC_Checkout->process_checkout()
> #18 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(303): WC_AJAX::checkout('')
> #19 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
> #20 /customers/4/2/3/website.com/httpd.www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
> #21 /customers/4/2/3/website.com/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_checkou...')
> #22 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(303): WC_AJAX::do_wc_ajax('')
> #23 /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(false, Array)
> #24 /customers/4/2/3/website.com/httpd.www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
> #25 /customers/4/2/3/website.com/httpd.www/wp-includes/template-loader.php(13): do_action('template_redire...')
> #26 /customers/4/2/3/website.com/httpd.www/wp-blog-header.php(19): require_once('/customers/4/2/...')
> #27 /customers/4/2/3/website.com/httpd.www/index.php(17): require('/customers/4/2/...')
> #28 {main}
>   thrown in /customers/4/2/3/website.com/httpd.www/wp-includes/class-wp-hook.php on line 305

**Comment by NemoTH70** [comment]
Wordpress 6.0 / Woocomerce 6.6.1 / PHP 7.4.30  - work fine without errors.

**Comment by aashishgurung** [comment]
@hellcoderGIT Sorry for the issue. We have already made our plugin compatible with PHP 8.x. Please try out our latest version.

We will close the ticket. If you think this is still relevant, please feel free to reopen it and we’ll take another look. Thank you.
