### ISSUE TITLE
Please - Need AVS verification for US/UK/Canada card holders

### ISSUE THREAD

**Issue by NemoTH70** [omise/omise-woocommerce#286]
Hello,

I know you're are very busy, but can you please implement AVS (Address Verification System) to better support North American credit cards. actually almost 100% of US/UK/canada transactions are rejected.

For more information: https://www.omise.co/How-to-improve-my-authorization-rate-for-US-UK-and-Canadian-cardholders
I really hope you can help us with this issue. Thanks in advance for your help.
Sam

**Comment by aashishgurung** [comment]
Hi @NemoTH70,

We have implemented AVS with our new 3DSv2 that was released on Oct 15, 2022. You should not get any issue with USA/UK/Canada card holders.
