### ISSUE TITLE
Not translatable with GrotPress.

### ISSUE THREAD

**Issue by mayukojpn** [omise/omise-woocommerce#31]
This plugin is not translatable on GlotPress, the tool which allows every locale team to manage WordPress plugin translation and generate/provide language pack.
https://translate.wordpress.org/projects/wp-plugins/omise
https://translate.wordpress.org/projects/wp-plugins/omise/language-packs
- [x] Text domain should be same as directory name.
- [x] Replace `Omise_Util::translate` with native gettext.

**Comment by guzzilar** [comment]
@mayukojpn Hi.
Sorry for leave this ticket sitting here for so long. We just released Omise-WooCommerce v3.0 that will support GlotPress as well.

Thanks for contributed on this one!

Cheers,
Nam

**Comment by mayukojpn** [comment]
Thanks! I finished all translation and [released first language pack for Japanese locale](https://translate.wordpress.org/projects/wp-plugins/omise/language-packs)! 🎉

I imported original translation from [languages/omise-ja.po](https://github.com/omise/omise-woocommerce/blob/master/languages/omise-ja.po) and validate some strings by using [WordPress Japanese style guide](https://wpdocs.osdn.jp/WordPress_%E3%81%AE%E7%BF%BB%E8%A8%B3/%E7%BF%BB%E8%A8%B3%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3) and glossary, and Omise dashboard. I also created [glossary for the plugin](https://translate.wordpress.org/projects/wp-plugins/omise/dev/ja/default/glossary).

**Comment by guzzilar** [comment]
@mayukojpn お疲れ様でした！！　_(am I using it correctly? 😂 )_

That is really nice, I'll check on it soon.
Appreciate! 👍
