### ISSUE TITLE
PHP 7.0

### ISSUE THREAD

**Issue by ZekSK** [omise/omise-woocommerce#33]
Hello,

we have updated PHP to 7.0 due to WooCommerce and WordPress 4.7.1 compatibility, however, our Omise gateway has completely stopped working.
Could you please provide some information on how to fix this?

Shop URL: https://www.siamtravel.net/tour/elephant-trekking-animal-shows-funny-day-safari
You can test it out by choosing a date + some people, going through checkout and adding some random info there, after choosing Omise (it is in test mode now), when you will try to Place Order, errors will appear on chrome console.

Thanks.

**Comment by guzzilar** [comment]
Hi @ZekSK 

I have tested at your website and cannot find the issue you mentioned.

Could you provide more information that we can use for investigate the issue, such as:
- The exact PHP version you're using (i.e. PHP 7.0.0 ~ 7.0.15).
- Screenshot of the error that you saw from Chrome Console.
- WooCommerce version.

Cheers,
Nam.

**Comment by guzzilar** [comment]
Hi @ZekSK 
Im going to close this ticket since there was no response and cannot reproduce the issue.

However, feel free to create a new ticket or reopen this one if you find any issues 🙂
