### ISSUE TITLE
Mobile banking doesn't work (URGENT)

### ISSUE THREAD

**Issue by vamsi444media** [omise/omise-woocommerce#412]
Hello,
We have been facing this weird problem that mobile banking options are not working and showing this message.

![WhatsApp Image 2023-11-02 at 8 20 11 AM](https://github.com/omise/omise-woocommerce/assets/149644207/f3fae51d-758b-4d52-8406-bb813fb01575)

Kindly help us to fix this very urgent.

Regards,
Vamsi J

**Comment by danfowler** [comment]
Thanks @vamsi444media for raising. We're aware of the issue and a fix will be ready soon.

**Comment by aashishgurung** [comment]
@vamsi444media We have released a PATCH version to fix the issue. Please upgrade to the new version.

**Comment by aashishgurung** [comment]
We are going to close this since we have released a PATCH version that fixes the bug raised by this issue. If this issue is still relevant, please feel free to reopen it with more details and we’ll take another look.
