### ISSUE TITLE
Plugin does not support USD currency

### ISSUE THREAD

**Issue by zeally** [omise/omise-woocommerce#55]
I got this error while testing Omise credit card payment in test mode with WooCommerce currency setting as "United States Dollar ($)".

Seems we cannot process your payment properly:
amount must be greater than or equal to 2000 (thb subunits). $0.09 converts to approximately 288 (thb subunits) and amount must be an integer

**Comment by guzzilar** [comment]
@zeally Hi

Currently the plugin hasn't supported multi-currency feature yet (Im working on this now :)).

**Comment by zeally** [comment]
@guzzilar Sound great. Thank you very much 😃 

Also, thank you for the version 3.0 update.

**Comment by guzzilar** [comment]
👍 welcome 😄

**Comment by guzzilar** [comment]
@zeally Hi, USD currency has been supported at release v3.2 (PR #84).
You can download it right away either from this repository or https://wordpress.org/plugins/woocommerce

> Note, this currency can be used only with Omise Thailand-registered account.
> Ref: https://www.omise.co/currency-and-amount.

Cheers!

**Comment by zeally** [comment]
@guzzilar ขอบคุณมากๆ ครับ เดี๋ยวผมจะลองใช้ดูและแจ้งให้ทราบหากพบบั๊กนะครับ

**Comment by guzzilar** [comment]
@zeally ยินดีครับ
ถ้ามีอะไรให้ช่วยเพิ่มเติม สามารถเปิด issue ใหม่ได้เลยนะครับ :D

**Comment by wickstargazer** [comment]
bump.. is this working now? i am still getting the error?

**Comment by guzzilar** [comment]
@wickstargazer It should work properly by Omise-WooCommerce v3.2.
Have you get any trouble using USD currency with Omise-WooCommerce on your store?

**Comment by wickstargazer** [comment]
I got to contact them, they will sort it out :) thankz
