### ISSUE TITLE
Omise v3.0 doesn't support for legacy WooCommerce (v2.x)

### ISSUE THREAD

**Issue by guzzilar** [omise/omise-woocommerce#57]
There is a [request](https://forum.omise.co/t/omise-version-3-0-not-compatibility-with-woocommerce-2-6-14/150/3) from our merchant asking for Omise-WooCommerce v3.0 to support WooCommerce v2.6.14.

I've investigated and found that there are some WooCommerce's functions (from WooCommerce v3.x) that have been using in Omise-WooCommerce v3.0 that hadn't existed in WooCommerce v2.x

For example, in `WooCommerce v3.x` there is a function called `WC_Abstract_Order::get_currency()`. But in `WooCommerce v2.x` it instead, calls `WC_Abstract_Order::get_order_currency()`.

There are some more, those made Omise-WooCommerce cannot be used with WooCommerce `2.x`.

---

This ticket is here to discuss and provide an update on this issue.

All thought and suggestions are welcome as well :)

**Comment by samart-ting** [comment]
I also stuck this issue as well. 
Here is the error log.

The WC_Order::get_order_currency function is deprecated since version 3.0. Replace with WC_Order::get_currency.

**Comment by guzzilar** [comment]
@samart-ting Hi, were you enabling `debug mode` when you found that error message?
And can you let me know which WooCommerce version you are currently using? 

Thanks.

**Comment by guzzilar** [comment]
Note: This issue has been solved in the release v3.1 
For more information, please check [Omise-WooCommerce v3.1 Release Note](https://github.com/omise/omise-woocommerce/releases/tag/v3.1)
