### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by fred** [omise/omise-woocommerce#6]
1. Refactor error messages and functions. Make functions smaller and simpler to debug.
2. Add auto-capture settings, and button to call the charge with capture.
3. Implement full and partial refunds, a button on the order item.
3. Implement account balance, some sort of Omise Dashboard page with Total and Available balance.

**Comment by guzzilar** [comment]
according to this issue.
I finished no. 1, 2, 4 here: https://github.com/omise/omise-woocommerce/pull/18

So, I'll open another issue for number 3 only and close this one.
