### ISSUE TITLE
Improve checkout form

### ISSUE THREAD

**Issue by fred** [omise/omise-woocommerce#7]
The checkout form needs the following improvements:
- [ ] Change card date to a dropdown list with data that Omise API accepts.  Instead of using input use select. (https://github.com/omise/omise-woocommerce/pull/14)
- [ ] Add option to translate and change field / Button texts for multilingual websites
- [ ] Add Omise seal logo (Secured by Omise)

**Comment by fred** [comment]
@guzzilar :tada:

**Comment by guzzilar** [comment]
@fred Hi hi, Im going to close this ticket due to a lot of changes in the new version of Omise-WooCommerce (v3.0). 

Sorry to not keep this ticket in touch, anyway, feel free to resubmit any issues if you find in v3.0!
Thanks!
