### ISSUE TITLE
Automatic Recurring Payments

### ISSUE THREAD

**Issue by mattpill** [omise/omise-woocommerce#72]
Hi, I’m looking to use the Omise card payment gateway as an automatic recurring payment option when a user add a subscription product. Does this plugin currently have the ability to do this?

If this is possible, how can you set this up?

If its not possible, will this be something that will be added in the future?

Thanks in advance!

**Comment by ploynaksuksri** [comment]
Hi, Any updates? ;)

**Comment by aashishgurung** [comment]
There are no plans for this. We are closing this for now since there hasn’t been any activity for a while. If you still think that this is relevant, please feel free to reopen it and we’ll take another look.
