### ISSUE TITLE
Fatal error, if install Omise plugin before WooCommerce

### ISSUE THREAD

**Issue by nimid** [omise/omise-woocommerce#78]
WordPress can not be operated both frontend and backend, if Omise plugin has been installed and activated before installing WooCommerce.

The error message is shown in the screenshots below.

**Frontend**

<img width="1280" alt="frontend-error" src="https://user-images.githubusercontent.com/4145121/32128182-fb16c880-bba5-11e7-8ed4-8826b2a65d81.png">

**Backend**

<img width="1280" alt="backend-error" src="https://user-images.githubusercontent.com/4145121/32128188-040a99a8-bba6-11e7-81e8-1cfd7439f553.png">

WordPress 4.8.2
Omise WooCommerce 3.1

**Steps to reproduce**

- Fresh install WordPress
- Go to backend, Plugins > Add New
- Install Omise plugin (WooCommerce has not been installed)
- Activate Omise plugin

Although, WooCommerce has been installed and activated before Omise plugin, if WooCommerce has been deactivated, the error result is the same.

**Comment by guzzilar** [comment]
@nimid Thanks for the report. I'll make patch to solve this on the next release.

**Comment by guzzilar** [comment]
Note: this issue has been solved at release [v3.2](https://github.com/omise/omise-woocommerce/releases/tag/v3.2) (PR #83, #88).
