### ISSUE TITLE
Add filter hooks for charge.description and charge.metadata

### ISSUE THREAD

**Issue by Thammada** [omise/omise-woocommerce#80]
There should be a way to modify/extend charge.description and charge.metadata when creating a charge.
I suggest adding a filter hook such that developers can modify the those properties programmatically. Admin UI for those fields can be created based on these filters.

**Comment by guzzilar** [comment]
@Thammada That's good idea. But I might not be able to make it in soon. 
If you're already working on it and interest to patch it in, please feel free to submit your pull request to this repo :)
