### ISSUE TITLE
any plans for this to support Bill Payment ?

### ISSUE THREAD

**Issue by ismannen** [omise/omise-woocommerce#82]
any plans for this to support Bill Payment ?

it shuld be nice if this could support Tesco Lotus bill payment if possible

**Comment by guzzilar** [comment]
@ismannen This topic has been discussing internally.
Anyway, I may not be able to give you the estimation timeline at this moment but, thanks for the question. I'll comeback to update its status in this ticket later once we have some news on it 👍

**Comment by guzzilar** [comment]
@ismannen Hi, just want to let you know, the feature has been implemented and is under the review process at the moment. Related pull requests: #122, #125, #126 

Feel free to contribute by helping us review those pull requests ;)

**Comment by guzzilar** [comment]
@ismannen Hi, the feature has been released at Omise-WooCommerce v3.7 and now available on https://wordpress.org/plugins/omise.
