### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by autsada** [omise/omise-woocommerce#89]
We have already have live dashboard and set public key and secret key. However, the payment process is not processed, it shows authentication failed after customer confirm their payment.

**Comment by guzzilar** [comment]
@autsada Hi, can you make sure that you put keys at those `Public key for live` and `Secret key for live` fields properly and also uncheck the `test mode` option at the payment setting page?
Reference: https://github.com/omise/omise-woocommerce#connect-your-store-with-your-omise-account

**Comment by keeratita** [comment]
@autsada just FYI, you can also check the format of those keys by this document as well (https://www.omise.co/api-authentication).

Hope this helps. :)

**Comment by autsada** [comment]
@guzzilar @keeratita . I solved this problem already.
Than you for quick reply.

**Comment by guzzilar** [comment]
cool, great to hear that :D
