### ISSUE TITLE
Support for installment payment ?

### ISSUE THREAD

**Issue by piyasil** [omise/omise-woocommerce#92]
I'd love to see the installment payment feature on this plugin. Do you have any plan to update the feature soon ?

**Comment by jacstn** [comment]
yes... It is our highest priority.
woocommerce is second after magento for instalment to be delivered.

So soon.

**Comment by guzzilar** [comment]
@piyasil @jacstn Hi, sorry for forgetting to letting you know, this feature has been released already and you can download from the latest Omise-WooCommerce version directly at WordPress Plugin Store: https://wordpress.org/plugins/omise
